from data_source import predictions_indexes_last_month, predictions_last_month
from plotter import plot_based_on_indexes_and_data


plot_based_on_indexes_and_data(predictions_indexes_last_month, predictions_last_month)